Resources:
  FlaskAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: flask-app-service
      InstanceConfiguration:
        Cpu: "1024"  # CPU allocation (in CPU units, 1024 = 1 vCPU)
        Memory: "2048"  # Memory allocation (in MB)
      SourceConfiguration:
        ImageRepository:
          ImageRepositoryType: ECR
          ImageIdentifier: "381492212823.dkr.ecr.us-east-1.amazonaws.com/mystery-flask-repo:latest"
          ImageConfiguration:
            Port: "8080"  # The port where the application listens
Outputs:
  FlaskAppURL:
    Value: !Sub "https://${FlaskAppRunnerService.ServiceUrl}"
    Description: "The URL where the Flask app is accessible via App Runner."
